package ru.itis.summer.practice26.ui

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.Button
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController
import ru.itis.summer.practice26.model.FilmsListScreen
import ru.itis.summer.practice26.repository.FilmsRepository
import ru.itis.summer.practice26.utils.DefaultPaddings

@Composable
fun GenerateFilmsScreen(
    navController: NavController
) {
    var inputValue by remember { mutableStateOf("") }
    var isListGenerated by remember { mutableStateOf(false) }

    val enteredNumber = inputValue.toIntOrNull()
    val isGenerateButtonEnabled = enteredNumber != null && enteredNumber > 0

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(horizontal = DefaultPaddings.horizontal, vertical = DefaultPaddings.vertical)
    ) {
        OutlinedTextField(
            value = inputValue,
            onValueChange = { newValue ->
                inputValue = newValue
                isListGenerated = false
            },
            label = { Text("Количество фильмов") },
            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            onClick = {
                FilmsRepository.generateFilms(enteredNumber ?: 0)
                isListGenerated = true
            },
            enabled = isGenerateButtonEnabled,
            modifier = Modifier.fillMaxWidth()
        ) {
            Text("Сгенерировать")
        }

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            onClick = { navController.navigate(FilmsListScreen) },
            enabled = isListGenerated,
            modifier = Modifier.fillMaxWidth()
        ) {
            Text("Перейти к списку")
        }
    }
}